// This is the VST3 equivalent of examples/ClapPlugin/plugin_entry.cpp.
// The BEGIN_FACTORY/DEF_CLASS2/END_FACTORY macros generate the
// GetPluginFactory() export that hosts call to discover the plugin --
// the VST3 counterpart of CLAP's clap_entry/get_factory().
//
// public.sdk/source/main/{macmain.cpp,linuxmain.cpp,dllmain.cpp} (pulled in
// automatically by the smtg_add_vst3plugin() CMake helper) provide the
// platform-specific module init/exit and DLL/bundle export glue around this.

#include "version.h"  // for FULL_VERSION_STR, generated by smtg_target_configure_version_file()
#include "vst3_plugin.h"

#include <pluginterfaces/vst/ivstaudioprocessor.h>
#include <pluginterfaces/vst/vsttypes.h>
#include <public.sdk/source/main/pluginfactory.h>

#define stringPluginName "Example VST3 Plugin"

BEGIN_FACTORY_DEF("Observe", "https://observe.dev", "mailto:info@observe.dev")

DEF_CLASS2(INLINE_UID_FROM_FUID(kVst3PluginProcessorUID),
           Steinberg::PClassInfo::kManyInstances,  // cardinality
           kVstAudioEffectClass,  // the component category (do not changed this)
           stringPluginName,  // here the plug-in name (to be changed)
           Steinberg::Vst::kDistributable,  // means that component and controller can be
           // distributed on different computers
           "Fx",  // Subcategory for this plug-in (to be changed)
           FULL_VERSION_STR,  // Plug-in version (to be changed)
           kVstVersionString,  // the VST 3 SDK version (do not changed this,
           // use always this define)
           Vst3Plugin::createInstance)  // function pointer called when this component
// should be instantiated

END_FACTORY
