#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake's smtg_target_configure_version_file()
#include "projectversion.h"

#define stringOriginalFilename "ExampleVst3Plugin.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Example VST3 Plugin (64Bit)"
#else
#define stringFileDescription "Example VST3 Plugin"
#endif
#define stringCompanyWeb "https://observe.audio"
#define stringCompanyEmail "mailto:info@observe.audio"
#define stringCompanyName "Observe"
#define stringLegalCopyright "Copyright(c) 2026 Observe Audio, LLC"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
